/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bagaturchess_egtb_gaviota_EGTBProbing */

#ifndef _Included_bagaturchess_egtb_gaviota_EGTBProbing
#define _Included_bagaturchess_egtb_gaviota_EGTBProbing
#ifdef __cplusplus
extern "C" {
#endif
#undef bagaturchess_egtb_gaviota_EGTBProbing_NATIVE_WHITE_TO_MOVE
#define bagaturchess_egtb_gaviota_EGTBProbing_NATIVE_WHITE_TO_MOVE 0L
#undef bagaturchess_egtb_gaviota_EGTBProbing_NATIVE_BLACK_TO_MOVE
#define bagaturchess_egtb_gaviota_EGTBProbing_NATIVE_BLACK_TO_MOVE 1L
#undef bagaturchess_egtb_gaviota_EGTBProbing_NATIVE_INFO_DRAW
#define bagaturchess_egtb_gaviota_EGTBProbing_NATIVE_INFO_DRAW 0L
#undef bagaturchess_egtb_gaviota_EGTBProbing_NATIVE_INFO_WMATE
#define bagaturchess_egtb_gaviota_EGTBProbing_NATIVE_INFO_WMATE 1L
#undef bagaturchess_egtb_gaviota_EGTBProbing_NATIVE_INFO_BMATE
#define bagaturchess_egtb_gaviota_EGTBProbing_NATIVE_INFO_BMATE 2L
#undef bagaturchess_egtb_gaviota_EGTBProbing_NATIVE_INFO_FORBID
#define bagaturchess_egtb_gaviota_EGTBProbing_NATIVE_INFO_FORBID 3L
#undef bagaturchess_egtb_gaviota_EGTBProbing_NATIVE_INFO_UNKNOWN
#define bagaturchess_egtb_gaviota_EGTBProbing_NATIVE_INFO_UNKNOWN 7L
#undef bagaturchess_egtb_gaviota_EGTBProbing_NATIVE_PID_NONE
#define bagaturchess_egtb_gaviota_EGTBProbing_NATIVE_PID_NONE 0L
#undef bagaturchess_egtb_gaviota_EGTBProbing_NATIVE_PID_PAWN
#define bagaturchess_egtb_gaviota_EGTBProbing_NATIVE_PID_PAWN 1L
#undef bagaturchess_egtb_gaviota_EGTBProbing_NATIVE_PID_KNIGHT
#define bagaturchess_egtb_gaviota_EGTBProbing_NATIVE_PID_KNIGHT 2L
#undef bagaturchess_egtb_gaviota_EGTBProbing_NATIVE_PID_BISHOP
#define bagaturchess_egtb_gaviota_EGTBProbing_NATIVE_PID_BISHOP 3L
#undef bagaturchess_egtb_gaviota_EGTBProbing_NATIVE_PID_ROOK
#define bagaturchess_egtb_gaviota_EGTBProbing_NATIVE_PID_ROOK 4L
#undef bagaturchess_egtb_gaviota_EGTBProbing_NATIVE_PID_QUEEN
#define bagaturchess_egtb_gaviota_EGTBProbing_NATIVE_PID_QUEEN 5L
#undef bagaturchess_egtb_gaviota_EGTBProbing_NATIVE_PID_KING
#define bagaturchess_egtb_gaviota_EGTBProbing_NATIVE_PID_KING 6L
#undef bagaturchess_egtb_gaviota_EGTBProbing_NATIVE_SQUARE_NONE
#define bagaturchess_egtb_gaviota_EGTBProbing_NATIVE_SQUARE_NONE 64L
/* Inaccessible static: singleton */
/*
 * Class:     bagaturchess_egtb_gaviota_EGTBProbing
 * Method:    init
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_bagaturchess_egtb_gaviota_EGTBProbing_init
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     bagaturchess_egtb_gaviota_EGTBProbing
 * Method:    probeHard
 * Signature: (III[I[I[B[B[I)Z
 */
JNIEXPORT jboolean JNICALL Java_bagaturchess_egtb_gaviota_EGTBProbing_probeHard
  (JNIEnv *, jobject, jint, jint, jint, jintArray, jintArray, jbyteArray, jbyteArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
